命令稿啟動於 2017年03月14日 (週二) 14時46分10秒
[1;32marlen@arlen-V5-473G[00m:[1;33m~/project/c_plus_language/hw[1;36m[00m$ wham[K[Koamil[K;pwd
arlen
/home/arlen/project/c_plus_language/hw
[1;32marlen@arlen-V5-473G[00m:[1;33m~/project/c_plus_language/hw[1;36m[00m$ git config -l
user.email=htoatot@gmail.com
user.name=ArlenPP
[1;32marlen@arlen-V5-473G[00m:[1;33m~/project/c_plus_language/hw[1;36m[00m$ git con[K[Klone http;[K://github.com/Ar lenPP/gi[K[Klab1.c[Kgit
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
[1;32marlen@arlen-V5-473G[00m:[1;33m~/project/c_plus_language/hw[1;36m[00m$ exit

命令稿已於 2017年03月14日 (週二) 14時47分07秒
 完成